services:
  calibre:
    image: lscr.io/linuxserver/calibre:8.13.0
    container_name: calibre
    # security_opt:
    #   - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      # - PASSWORD= #optional
      # - CLI_ARGS= #optional
    volumes:
      - /mnt/wd-green/calibre:/config
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped